# SPDX-License-Identifier: Apache-2.0
# Copyright (c) VEXXHOST, Inc.

galaxy_info:
  author: VEXXHOST, Inc.
  description: Ansible role for secretgen-controller
  license: Apache-2.0
  min_ansible_version: 5.5.0
  standalone: false
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies:
  - role: defaults
  - role: vexxhost.kubernetes.upload_helm_chart
    vars:
      upload_helm_chart_src: "{{ secretgen_controller_helm_chart_path }}"
      upload_helm_chart_dest: "{{ secretgen_controller_helm_chart_ref }}"
