apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secretgen-controller.fullname" . }}
rules:
- apiGroups:
  - secretgen.k14s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - secretgen.carvel.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
